# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f933bdeb35987fea81f500a3f2c2c0f5d12c26314fcc2211725abb282e6a3289eda1ea06ce6630e476f8c78a04062c03df4db09672a54fbd8de7443be52c1918

test:
  secret_key_base: ac92d86760a43e993e0912b90634d130b63cbc5a5fc0819c4bafc8cfda3c3b13e9fa3a79eafcb9402bbf0eaaa01953a513c6bd0e86d1c22e45dc2696d4ccd4e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
